### ISSUE TITLE
Adding a key to the thumb cluster

### ISSUE THREAD

**Issue by fi0** [sanderboer/chonkybois#1]
Thank you for sharing the model!
Is the generator script available? I'm trying to add a key to the thumb cluster and would love some tips :)

**Comment by sanderboer** [comment]
The script is embedded in the generator.blend file.
Change the script at line 250 to:

thumb_grid = grid(rows=3, cols=1, edge_align=False, gutter=2, grid_width=28.75, alpha=1, beta=1)

press the play button in the title bar of the script editor, 
Now start futzing around line 274 to place and orient the thumbcluster
`for o in ['thumb_fill', 'thumb_plate','thumb_alps_cav']:
    mesh_trans(bpy.data.objects[o], ry=10)
    mesh_trans(bpy.data.objects[o], rx=20)
    mesh_trans(bpy.data.objects[o], rz=-77)

    mesh_trans(bpy.data.objects[o], dx=-105)
    mesh_trans(bpy.data.objects[o], dy=-61)
    mesh_trans(bpy.data.objects[o], dz=0)
`
dx moves it left, dz moves it up/down in mm.

**Comment by fi0** [comment]
Thank you very much! I'll try.

**Comment by fi0** [comment]
How do I generate the case after modifying generator.blend?
Or, how do I link up the lil_chonky_bois.blend with generator.blend?

**Comment by sanderboer** [comment]
I'm afraid you have to model it yourself.
What I would do is this:
- save the generator model with the new base meshes as a new file
- join the base thumbplate and the base mountplate into a single mesh (ctrl-j with both meshes selected)
- add a solidify modifier to this mesh, set thickness to 4-ish
- join the thumb and base cavity meshes similarly, make sure you combine the right cavity meshes (alps vs cherry, cherry is square, alps are oblong)
- add a solidify modifier to the cavity mesh also, but set thickness to 20-ish,
- add a boolean modifier to the base mount plate mesh from earlier and select the cavity mesh as the mesh to cut with, (this is why I call it a cavity mesh). Result should be a mountplate with holes for switches.
- select the base mesh, go into edit mode (press tab to toggle object and edit mode) and add faces between thumb and base.
- rename the base mesh to something sensible

Now save this file and open another blender instance, load the lilchonky model.
When you inspect my keyboard model (mauc_kb.002 if I recall correctly) you see that this model has a huge modifier stack.
The second modifier from the top is a boolean Add modifier.
Now file->append and select your file where you saved your sensibly named mountplate, -> Object -> your sensibly named object 
Now you have your new sensibly named mountplate (and the mesh used in the cavity boolean) in this file.

Select the mauc_kb.002 model and go into the modifier stack, find the add boolean where my mount_plate_alps_edit is added to the kb and swap it for your mountplate model.   
You should now have a model of a keyboard with your mountplate and it will probably not fit, now it is time to adjust the mesh of the model by hand to make all fit.

**Comment by fi0** [comment]
Thank you for the writeup! I'll learn more about blender first :p
